//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BTTLib {

public enum btt_tracking_mode_t {
  BTT_COUNT_IN_TRACKING,
  BTT_ONSET_TRACKING,
  BTT_ONSET_AND_TEMPO_TRACKING,
  BTT_ONSET_AND_TEMPO_AND_BEAT_TRACKING,
  BTT_TEMPO_LOCKED_BEAT_TRACKING,
  BTT_METRONOME_MODE,
  BTT_NUM_TRACKING_MODES
}

}
