//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace BTTLib {

public enum filter_window_t {
  FILTER_WINDOW_RESERVED = 0,
  FILTER_WINDOW_RECT,
  FILTER_WINDOW_BARTLETT,
  FILTER_WINDOW_HANN,
  FILTER_WINDOW_HAMMING,
  FILTER_WINDOW_BLACKMANN
}

}
